### ISSUE TITLE
Bugs in Attribute Parser ...

### ISSUE THREAD

**Issue by Tom-Cuthill** [bertt/mapbox-vector-tile-cs#10]
The AttributeParser does not currently handle sIntValues and the code is incorrect for uInts.  The bottom of the GetAttr method should look like this:

            else if(value.HasSIntValue)
            {
                res = value.SintValue;
            }
            else if (value.HasUIntValue)
            {
                res = value.UintValue;
            }

Cheers,
Tom Cuthill

**Comment by bertt** [comment]
Thanks for noticing! Fixed in https://github.com/bertt/mapbox-vector-tile-cs/commit/73165c428bb49cc30c64452cada469c45f5f9a9e , published new NuGet package 3.1.4

**Comment by bertt** [comment]
maybe you can attach a test tile with sIntValues and UintValues? So I can add tests on it.

**Comment by Tom-Cuthill** [comment]
This pbf contains a cadastral tile which includes a signed int value in its gid attribute.

[cadastral.zip](https://github.com/bertt/mapbox-vector-tile-cs/files/762345/cadastral.zip)

**Comment by bertt** [comment]
thanks test is added https://github.com/bertt/mapbox-vector-tile-cs/commit/25aea906d6e5205283158f9e706c96d72e433aab
