### ISSUE TITLE
Zero integer values lost on serialization

### ISSUE THREAD

**Issue by rouen-sk** [bertt/mapbox-vector-tile-cs#16]
Hi, first thing first - great project, huge timesaver. I know it is intended only as decoder, but I am using it with success to do minor edits to vector tiles - deserialize, rename some layers, remove some layers, remove some features from layers, and serialize back. It generally works great, with one exception - attributes (properties) which are for example integer value zero, and are correctly deserialized as `HasIntValue=true` and `IntValue=0` are not correctly serialized back (if you deserialize the tile serialized this way, `HasIntValue' is `false` in that `Value` object. 
Do you think this can be fixed easily somehow? Thanks!

**Comment by bertt** [comment]
Hi, can you provide a (minimal) reproducible case? Thanks.

**Comment by rouen-sk** [comment]
Sure, I can provide real-world case (it is not minimal, but i want to use untouched tile, as generated by mapnik-vector-tile, to prevent any errors on my side). 

See tile attached. `Layers[4]` is layer named `road___1`. `Values[1]` in this layer is our subject: `HasIntValue=true` and `IntValue=0`. 

Now just deserialize it into stream, serialize it back (save it to file maybe, i do that), deserialize this new file, and the same `Value` object will be `HasIntValue=false` (in fact, it has all of the `HasAnythingValue` false, so I guess it is invalid.

[16_34440_23455_raw.zip](https://github.com/bertt/mapbox-vector-tile-cs/files/1775440/16_34440_23455_raw.zip)

**Comment by bertt** [comment]
started a unit test to reproduce this issue, see https://github.com/bertt/mapbox-vector-tile-cs/blob/master/tests/mapbox.vector.tile.tests/DeserializeSerializeBackTests.cs

if you can add some missing code it will be great, otherwise I'll complete it later this week.

**Comment by bertt** [comment]
Thanks I've added the code from https://github.com/bertt/mapbox-vector-tile-cs/commit/067c508c2ac19448ee2ddbaa40d8748838dada44#commitcomment-27925502

unit test is indeed failing, let's find a way to fix it

**Comment by bertt** [comment]
so this only happens when attribute type=int and value=0? or also with other types?

**Comment by bertt** [comment]
unit test is working when changing https://github.com/bertt/mapbox-vector-tile-cs/blob/master/src/VectorTile.cs#L68 from '[System.ComponentModel.DefaultValue(default(long))]' to '[System.ComponentModel.DefaultValue(int.MinValue)]' 

lets determine impact for other types.

**Comment by rouen-sk** [comment]
my guess is that is happens when the value is default for the particular type (such as 0 for Int32). Since empty string is not default for string, and nulls are not supported by MVT specification, I suspect no problem here. But of course, needs to be tested.

**Comment by bertt** [comment]
i've created a new NuGet package (4.0.1) can you try (once it's indexed)? 
https://www.nuget.org/packages/mapbox-vector-tile/4.0.1

**Comment by rouen-sk** [comment]
@bertt I dont use nuget package, I have sources cloned in my project, since I extended them slightly (for example implemented `System.IEquatable<Value>` on `Value`). 
Anyway - fix is not good. I applied changes in https://github.com/bertt/mapbox-vector-tile-cs/commit/76eaefc81c1a33426603d425ec64507889aaaf21 locally, and now the serialized-deserialized tile's `Value` has `HasFloatValue`, `HasIntValue` and `HasStringValue` set to true. 

Add to the unit test:
```
Assert.IsFalse(deserializedTile.Layers[4].Values[1].HasFloatValue);
Assert.IsFalse(deserializedTile.Layers[4].Values[1].HasStringValue);
```

**Comment by bertt** [comment]
ah ok, little bit too quick :-) I'll take a look later this week again

**Comment by rouen-sk** [comment]
sure, thanks, I will try to look into it too, but I am pretty swamped. Btw, I recommend you remove nuget 4.0.1. since it can cause regressions even for people not suffering the issue we are solving.

**Comment by bertt** [comment]
yes good idea, 4.0.1 is unlisted

**Comment by rouen-sk** [comment]
FYI, since I think this has basically nothing to do with mapbox-vector-tile-cs and it is protobuf-net issue, I raised the question there: https://github.com/mgravell/protobuf-net/issues/363

**Comment by bertt** [comment]
ok great! I've reverted VectorTile.cs so the back-to-back serialize unit test fails again. Als added the checks on HasFloatValue and HasStringValue

**Comment by rouen-sk** [comment]
So, guys from protobuf-net proposed easy solution for this, see https://github.com/mgravell/protobuf-net/issues/363#issuecomment-371161632

You just need to add this code into `Value` class, and done.
```
            public bool ShouldSerializeStringValue() => HasStringValue;
            public bool ShouldSerializeFloatValue() => HasFloatValue;
            public bool ShouldSerializeDoubleValue() => HasDoubleValue;
            public bool ShouldSerializeIntValue() => HasIntValue;
            public bool ShouldSerializeUIntValue() => HasUIntValue;
            public bool ShouldSerializeSIntValue() => HasSIntValue;
            public bool ShouldSerializeBoolValue() => HasBoolValue;
```

**Comment by bertt** [comment]
great it works, all unit tests working again. Closing this issue.
