### ISSUE TITLE
Is Grpc.AspNetCore implementation in the roadmap?

### ISSUE THREAD

**Issue by deaquino** [bertt/mapbox-vector-tile-cs#21]
Just to know if there are any plans to adapt it to the new gRPC approach.
Thanks

**Comment by bertt** [comment]
Hi, thats not on the roadmap for this library, because out of scope.  But it would be nice to see a client/server application using gRPC for vector tiles.

**Comment by bertt** [comment]
Closing

**Comment by bertt** [comment]
maybe something is possible using https://github.com/protobuf-net/protobuf-net.Grpc
