### ISSUE TITLE
could not support new tile format.

### ISSUE THREAD

**Issue by sendreams** [bertt/mapbox-vector-tile-cs#26]
the mvt file can't be deserialize.

the tile download by curl

curl --request GET \
  --url 'https://api.mapbox.com/v4/mapbox.mapbox-models-v1/15/16591/11270.vector.pbf?sku=101xe2aWG6Bmo&access_token=pk.eyJ1IjoibWFwYm94LW1hcC1kZXNpZ24iLCJhIjoiY2xrc2pzc2VuMDFybTNlcXQwOG9ieXFxeSJ9.tFV8YJxUOkHxcaZ70BQiUg' \
  --header 'Referer: https://labs.mapbox.com/' \

**Comment by ggyyso** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您的邮件已收到。

**Comment by bertt** [comment]
What error do you get? Maybe you have to unzip the file first.

**Comment by ggyyso** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您的邮件已收到。
