### ISSUE TITLE
Mapbox-vector-tile does not support MemoryStream

### ISSUE THREAD

**Issue by ScriptHound** [bertt/mapbox-vector-tile-cs#27]
The case is:

Im trying to read .pbf files from Rosreestr and in case where I want to transform them into MemoryStream and pass to mapbox-tile-server the library doesnt parse it. 

Example file
[1195.pbf.zip](https://github.com/bertt/mapbox-vector-tile-cs/files/14193609/1195.pbf.zip)

This example works totally fine
```C#
namespace test_mapbox;
using GeoJSON.Net.Feature;

using Mapbox.Vector.Tile;

class Program
{
    static void Main(string[] args)
    {
        using (var stream = File.OpenRead("test.pbf"))
        {
            var tile = VectorTileParser.Parse(stream);
            foreach (var layer in tile)
            {
                Console.WriteLine(layer.Name);
            }            
        }
    }
}

```

But when I try to:
```C#
var pbfFile = response.ResponseBinary;
var stream = new MemoryStream();
stream.Write(pbfFile, 0, pbfFile.Length);
var layers = VectorTileParser.Parse(stream); // This one returns zero length sequence
```

You can try download the file by yourself using this link https://pkk.rosreestr.ru/arcgis/rest/services/Hosted/caddivsion/VectorTileServer/tile/12/1190/2392.pbf but VPN within Russia is needed to access it

**Comment by ggyyso** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您的邮件已收到。

**Comment by bertt** [comment]
maybe it's gzip?

https://github.com/bertt/mapbox-vector-tile-cs/blob/master/tests/mapbox.vector.tile.tests/TileParserTests.cs#L88

**Comment by ScriptHound** [comment]
oh, thank you. Indeed my http client uses compression. Im going to check for it tomorrow

**Comment by ScriptHound** [comment]
Thank you again, it worked
