### ISSUE TITLE
add support for polygon inner- and outerrings

### ISSUE THREAD

**Issue by bertt** [bertt/mapbox-vector-tile-cs#4]

**Comment by pauldendulk** [comment]
In 3.0 polylgons only have outerrings?

**Comment by bertt** [comment]
in 3.0 a polygon with innerring will result wrongly in a multipolygon. Will be fixed in 3.1

**Comment by bertt** [comment]
(faling) unit test in https://github.com/bertt/mapbox-vector-tile-cs/blob/master/tests/mapbox.vector.tile.tests/MultiGeometryTests.cs#L10

**Comment by bertt** [comment]
fixed in 3.1
