### ISSUE TITLE
Not supported in a UWP application

### ISSUE THREAD

**Issue by ImCarrot** [bertt/mapbox-vector-tile-cs#5]
I tried to install in my UWP application and the nugget installation failed. The below is the log: 
`PM> Install-Package mapbox-vector-tile
Restoring packages for 'VectorMaps'.
Restoring packages for c:\users\ceinfo\documents\visual studio 2015\Projects\VectorMaps\VectorMaps\project.json...
  GET https://api.nuget.org/v3-flatcontainer/mapbox-vector-tile/index.json
  OK https://api.nuget.org/v3-flatcontainer/mapbox-vector-tile/index.json 1032ms
  GET https://api.nuget.org/v3-flatcontainer/mapbox-vector-tile/3.1.1/mapbox-vector-tile.3.1.1.nupkg
  OK https://api.nuget.org/v3-flatcontainer/mapbox-vector-tile/3.1.1/mapbox-vector-tile.3.1.1.nupkg 1194ms
Installing mapbox-vector-tile 3.1.1.
Install-Package : mapbox-vector-tile 3.1.1 is not compatible with UAP,Version=v10.0.
At line:1 char:1
+ Install-Package mapbox-vector-tile
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Some packages are not compatible with UAP,Version=v10.0.
At line:1 char:1
+ Install-Package mapbox-vector-tile
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : mapbox-vector-tile 3.1.1 is not compatible with UAP,Version=v10.0 (win10-arm).
At line:1 char:1
+ Install-Package mapbox-vector-tile
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Some packages are not compatible with UAP,Version=v10.0 (win10-arm).
At line:1 char:1
+ Install-Package mapbox-vector-tile
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : mapbox-vector-tile 3.1.1 is not compatible with UAP,Version=v10.0 (win10-arm-aot).
At line:1 char:1
+ Install-Package mapbox-vector-tile
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Some packages are not compatible with UAP,Version=v10.0 (win10-arm-aot).
At line:1 char:1
+ Install-Package mapbox-vector-tile
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : mapbox-vector-tile 3.1.1 is not compatible with UAP,Version=v10.0 (win10-x64).
At line:1 char:1
+ Install-Package mapbox-vector-tile
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Some packages are not compatible with UAP,Version=v10.0 (win10-x64).
At line:1 char:1
+ Install-Package mapbox-vector-tile
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : mapbox-vector-tile 3.1.1 is not compatible with UAP,Version=v10.0 (win10-x64-aot).
At line:1 char:1
+ Install-Package mapbox-vector-tile
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Some packages are not compatible with UAP,Version=v10.0 (win10-x64-aot).
At line:1 char:1
+ Install-Package mapbox-vector-tile
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : mapbox-vector-tile 3.1.1 is not compatible with UAP,Version=v10.0 (win10-x86).
At line:1 char:1
+ Install-Package mapbox-vector-tile
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Some packages are not compatible with UAP,Version=v10.0 (win10-x86).
At line:1 char:1
+ Install-Package mapbox-vector-tile
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : mapbox-vector-tile 3.1.1 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
At line:1 char:1
+ Install-Package mapbox-vector-tile
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Some packages are not compatible with UAP,Version=v10.0 (win10-x86-aot).
At line:1 char:1
+ Install-Package mapbox-vector-tile
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Package restore failed for 'VectorMaps'.
Install-Package : Package restore failed. Rolling back package changes for 'VectorMaps'.
At line:1 char:1
+ Install-Package mapbox-vector-tile
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 `

**Comment by bertt** [comment]
thanks, I can reproduce this issue. Shall have a look how to fix it. 
As a workaround for now you can download the source and change the build target.

**Comment by bertt** [comment]
Should work now with new NuGet package mapbox-vector-tile 3.1.3

**Comment by ImCarrot** [comment]
Thank for solving the issue, It works now. Can you please help me on how to use your nugget to provide vector Tiles to my Bing Map control in UWP apps.
