### ISSUE TITLE
.Net Standard support

### ISSUE THREAD

**Issue by pherbel** [bertt/mapbox-vector-tile-cs#8]
Hi,

Do you plan to support .Net Standard?

**Comment by bertt** [comment]
yes sure, was waiting for the dependencies to support it

**Comment by pauldendulk** [comment]
The v3.1.4 nuget package depends on the latest version of protobuf-net which is itself .NET Standard 1.3. So if you install it you get a .NET Standard package automatically, which is a problem for both PCLs and .NET Standard. I think it only works on regular .NET Framework.

Solutions:
- Max the nuspec dependency to an older version of protobuf-net (oddly this should be somewhere between 2.0 and 2.2).
- Move vector-tile-cs to .NET Standard 1.3 itself.

I vote for option two but don't know how if that's possible given the other dependencies.

**Comment by bertt** [comment]
Published 4.0 with .NET Standard 1.3 https://www.nuget.org/packages/mapbox-vector-tile/4.0.0
